[pytest]
testpaths = tests

addopts = 
    -v
    --strict-markers
    --alluredir=allure-results

markers = 
    smoke: Critical smoke tests
    regression: Regression test suite
    api: API automation tests
    ui: UI automation tests
    integration: Integration tests
    e2e: End-to-end tests

